# feature_extraction.py

import logging
import numpy as np
import torch
from torch import nn
from typing import Dict, List, Tuple
from scipy.signal import savgol_filter
from scipy.stats import gaussian_kde
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import make_pipeline
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.utils.validation import check_is_fitted
from sklearn.utils import check_array
from sklearn.exceptions import NotFittedError
from sklearn.utils._testing import ignore_warnings
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn.utils._testing import assert_warns
from sklearn.utils._testing import assert_raises
from sklearn.utils._testing import assert_equal
from sklearn.utils._testing import assert_almost_equal
from sklearn.utils._testing import assert_warns_message
from sklearn